# Generated by Django 3.1 on 2020-10-14 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=250)),
                ('author', models.CharField(default='', max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('publisher', models.CharField(max_length=100)),
                ('book_quantity', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('book_cover', models.JSONField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_pic', models.JSONField(null=True)),
                ('password', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_phone', models.CharField(default='', max_length=11)),
                ('order_delivery_address', models.CharField(max_length=250)),
                ('order_date', models.TextField()),
                ('order_status', models.CharField(default='New', max_length=10)),
                ('order_quantity', models.PositiveIntegerField(default=0)),
                ('order_price', models.PositiveIntegerField(default=0)),
                ('order_book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='book_id', to='Kawi_Application.books')),
                ('order_customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='Kawi_Application.customers')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_book_quantity', models.PositiveIntegerField(default=0)),
                ('cart_book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cart_book', to='Kawi_Application.books')),
                ('cart_customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cart_customer', to='Kawi_Application.customers')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
